spring:
  application:
    name: customer-management-backend
  datasource:
    url: jdbc:h2:mem:customer-management
  jpa:
    open-in-view: false

server:
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
        same-site: lax
